name: authentication_repository
version: 0.0.1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.1.3
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.4
  equatable: ^2.0.3
  cache:
    path: ../cache