name: form_inputs
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.1
dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
